/* URユニットのマスター（画面側の正本）。unit.html と profile-card.html の両方が読み込む。
   ㉚（2026-09-27）で unit.html の const UNITS から切り出した。自己紹介カードが入手日と実装日（released）を比べるため。
   id       ：実装順No（DBの units_master.unit_id と一致）
   name     ：ゲーム内の表記（運営の公式X・お知らせと同じ）。DBの units_master.name と一致させる。
              ㉚で統一：括弧は半角「()」、Ζ・ΖΖは半角英字「Z」「ZZ」（ゲーム内がこの表記のため。作品名＝works_masterはアニメの公式タイトルどおり「Ζ」）
              ゲーム内の名前の末尾に付く「(EX)」は付けない（画像でURと分かるため。2026-09-27 ユーザー決定）
   released ：ゲーム内の実装日（ガシャ初登場日・JST）。入手記録の入手日の初期値、カードの「実装日」表示に使う
   wrap     ：（任意）自己紹介カードで機体名を2行に折り返すときの改行位置を「|」で指定する。名前と「|」以外は一字一句同じにすること。
              空白・括弧・「・」・「ガンダム」の前後で自然に切れる名前には不要（㉚）
   新ユニット追加時はここに1行足す（checker/CLAUDE.md「新ユニット・作品の追加手順」） */
window.UR_UNITS = [
  {"id": 1, "name": "ガンダム", "limited": false, "type": "耐久", "imageUrl": "images/units/1.jpg", "released": "2025-04-16"},
  {"id": 2, "name": "ガンダムEz8", "limited": false, "type": "攻撃", "imageUrl": "images/units/2.jpg", "released": "2025-04-16"},
  {"id": 3, "name": "ストライカーカスタム", "limited": false, "type": "攻撃", "imageUrl": "images/units/3.jpg", "released": "2025-04-16"},
  {"id": 4, "name": "ル・シーニュ", "limited": false, "type": "支援", "imageUrl": "images/units/4.jpg", "released": "2025-04-16"},
  {"id": 5, "name": "νガンダム", "limited": false, "type": "支援", "imageUrl": "images/units/5.jpg", "released": "2025-04-16"},
  {"id": 6, "name": "サザビー", "limited": false, "type": "攻撃", "imageUrl": "images/units/6.jpg", "released": "2025-04-16"},
  {"id": 7, "name": "ユニコーンガンダム(デストロイモード)", "limited": false, "type": "攻撃", "imageUrl": "images/units/7.jpg", "released": "2025-04-16"},
  {"id": 8, "name": "ナラティブガンダムA装備", "limited": false, "type": "耐久", "imageUrl": "images/units/8.jpg", "released": "2025-04-16"},
  {"id": 9, "name": "クロスボーンガンダム", "limited": false, "type": "攻撃", "imageUrl": "images/units/9.jpg", "released": "2025-04-16"},
  {"id": 10, "name": "フリーダムガンダム", "limited": false, "type": "支援", "imageUrl": "images/units/10.jpg", "released": "2025-04-16"},
  {"id": 11, "name": "ガンダムエクシア", "limited": false, "type": "攻撃", "imageUrl": "images/units/11.jpg", "released": "2025-04-16"},
  {"id": 12, "name": "ガンダム・バルバトス(第6形態)", "limited": false, "type": "耐久", "imageUrl": "images/units/12.jpg", "released": "2025-04-16"},
  {"id": 13, "name": "ガンダム・エアリアル", "limited": false, "type": "支援", "imageUrl": "images/units/13.jpg", "released": "2025-04-16"},
  {"id": 14, "name": "フェニックスガンダム(能力解放)", "limited": false, "type": "支援", "imageUrl": "images/units/14.jpg", "released": "2025-04-16"},
  {"id": 15, "name": "ストライクフリーダムガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/15.jpg", "released": "2025-04-30"},
  {"id": 16, "name": "ジャスティスガンダム", "limited": false, "type": "耐久", "imageUrl": "images/units/16.jpg", "released": "2025-04-30"},
  {"id": 17, "name": "Zガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/17.jpg", "released": "2025-05-13"},
  {"id": 18, "name": "ジ・O", "limited": false, "type": "支援", "imageUrl": "images/units/18.jpg", "released": "2025-05-13"},
  {"id": 19, "name": "ガンダム試作2号機", "limited": true, "type": "支援", "imageUrl": "images/units/19.jpg", "released": "2025-05-31"},
  {"id": 20, "name": "シャア専用ザク", "limited": false, "type": "攻撃", "imageUrl": "images/units/20.jpg", "released": "2025-05-31"},
  {"id": 21, "name": "ガンダムデスサイズヘル(EW)", "limited": false, "type": "耐久", "imageUrl": "images/units/21.jpg", "released": "2025-06-16"},
  {"id": 22, "name": "ビルドストライクガンダム(フルパッケージ)", "limited": false, "type": "支援", "imageUrl": "images/units/22.jpg", "released": "2025-06-16"},
  {"id": 23, "name": "Hi-νガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/23.jpg", "released": "2025-06-30"},
  {"id": 24, "name": "フォースインパルスガンダム", "limited": false, "type": "支援", "imageUrl": "images/units/24.jpg", "released": "2025-06-30"},
  {"id": 25, "name": "フルアーマー・ガンダム(サンダーボルト版)", "limited": false, "type": "耐久", "imageUrl": "images/units/25.jpg", "released": "2025-07-14"},
  {"id": 26, "name": "サイコ・ザク", "limited": false, "type": "支援", "imageUrl": "images/units/26.jpg", "released": "2025-07-14"},
  {"id": 27, "name": "バンシィ・ノルン(デストロイモード)", "limited": true, "type": "耐久", "imageUrl": "images/units/27.jpg", "released": "2025-07-31"},
  {"id": 28, "name": "マスターガンダム", "limited": false, "type": "攻撃", "imageUrl": "images/units/28.jpg", "released": "2025-07-31"},
  {"id": 29, "name": "モンスターブラックドラゴン", "limited": true, "type": "支援", "imageUrl": "images/units/29.jpg", "released": "2025-08-08", "wrap": "モンスター|ブラックドラゴン"},
  {"id": 30, "name": "劉備ユニコーンガンダム", "limited": false, "type": "攻撃", "imageUrl": "images/units/30.jpg", "released": "2025-08-08", "wrap": "劉備|ユニコーンガンダム"},
  {"id": 31, "name": "フルアーマーZZガンダム", "limited": false, "type": "耐久", "imageUrl": "images/units/31.jpg", "released": "2025-08-31"},
  {"id": 32, "name": "キュベレイ(ZZ版)", "limited": true, "type": "攻撃", "imageUrl": "images/units/32.jpg", "released": "2025-08-31"},
  {"id": 33, "name": "ジオング", "limited": false, "type": "攻撃", "imageUrl": "images/units/33.jpg", "released": "2025-09-16"},
  {"id": 34, "name": "ガンダム・アスタロトリナシメント", "limited": false, "type": "支援", "imageUrl": "images/units/34.jpg", "released": "2025-09-16", "wrap": "ガンダム・アスタロト|リナシメント"},
  {"id": 35, "name": "ユニコーンガンダム(デストロイモード/覚醒)", "limited": true, "type": "支援", "imageUrl": "images/units/35.jpg", "released": "2025-09-30"},
  {"id": 36, "name": "ゴッドガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/36.jpg", "released": "2025-09-30"},
  {"id": 37, "name": "ガンダムF91", "limited": false, "type": "耐久", "imageUrl": "images/units/37.jpg", "released": "2025-09-30"},
  {"id": 38, "name": "ガンダム試作3号機", "limited": true, "type": "耐久", "imageUrl": "images/units/38.jpg", "released": "2025-10-10"},
  {"id": 39, "name": "ノイエ・ジール", "limited": false, "type": "攻撃", "imageUrl": "images/units/39.jpg", "released": "2025-10-10"},
  {"id": 40, "name": "ガンダム・バルバトスルプスレクス", "limited": true, "type": "攻撃", "imageUrl": "images/units/40.jpg", "released": "2025-10-31", "wrap": "ガンダム・バルバトス|ルプスレクス"},
  {"id": 41, "name": "ガンダム・エアリアル改修型", "limited": false, "type": "耐久", "imageUrl": "images/units/41.jpg", "released": "2025-10-31"},
  {"id": 42, "name": "ブルーディスティニー1号機", "limited": false, "type": "攻撃", "imageUrl": "images/units/42.jpg", "released": "2025-11-11"},
  {"id": 43, "name": "シナンジュ", "limited": false, "type": "支援", "imageUrl": "images/units/43.jpg", "released": "2025-11-11"},
  {"id": 44, "name": "Ξガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/44.jpg", "released": "2025-11-30"},
  {"id": 45, "name": "ペーネロペー", "limited": false, "type": "耐久", "imageUrl": "images/units/45.jpg", "released": "2025-11-30"},
  {"id": 46, "name": "プロヴィデンスガンダム", "limited": false, "type": "支援", "imageUrl": "images/units/46.jpg", "released": "2025-12-08"},
  {"id": 47, "name": "ケンプファー", "limited": false, "type": "攻撃", "imageUrl": "images/units/47.jpg", "released": "2025-12-08"},
  {"id": 48, "name": "ガンダム・キャリバーン", "limited": true, "type": "攻撃", "imageUrl": "images/units/48.jpg", "released": "2025-12-31"},
  {"id": 49, "name": "デスティニーガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/49.jpg", "released": "2025-12-31"},
  {"id": 50, "name": "ビグ・ラング", "limited": false, "type": "支援", "imageUrl": "images/units/50.jpg", "released": "2026-01-16"},
  {"id": 51, "name": "ガンダム・キマリスヴィダール", "limited": false, "type": "耐久", "imageUrl": "images/units/51.jpg", "released": "2026-01-16", "wrap": "ガンダム・キマリス|ヴィダール"},
  {"id": 52, "name": "ガンダムDX", "limited": true, "type": "攻撃", "imageUrl": "images/units/52.jpg", "released": "2026-01-31"},
  {"id": 53, "name": "ガンダムヴァサーゴチェストブレイク", "limited": false, "type": "支援", "imageUrl": "images/units/53.jpg", "released": "2026-01-31", "wrap": "ガンダムヴァサーゴ|チェストブレイク"},
  {"id": 54, "name": "ガンダムアストレイ レッドフレーム改", "limited": true, "type": "攻撃", "imageUrl": "images/units/54.jpg", "released": "2026-02-12"},
  {"id": 55, "name": "ガンダムアストレイ ゴールドフレーム天ミナ", "limited": false, "type": "耐久", "imageUrl": "images/units/55.jpg", "released": "2026-02-12"},
  {"id": 56, "name": "ガンダムAGE-2 ノーマル", "limited": true, "type": "支援", "imageUrl": "images/units/56.jpg", "released": "2026-02-28"},
  {"id": 57, "name": "ガンダムAGE-1", "limited": false, "type": "攻撃", "imageUrl": "images/units/57.jpg", "released": "2026-02-28"},
  {"id": 58, "name": "グフカスタム", "limited": false, "type": "耐久", "imageUrl": "images/units/58.jpg", "released": "2026-03-13"},
  {"id": 59, "name": "サイコ・ハロ", "limited": false, "type": "攻撃", "imageUrl": "images/units/59.jpg", "released": "2026-03-13"},
  {"id": 60, "name": "ウイングガンダムゼロ(EW)", "limited": true, "type": "攻撃", "imageUrl": "images/units/60.jpg", "released": "2026-04-01"},
  {"id": 61, "name": "ダブルオーライザー(最終決戦仕様)", "limited": true, "type": "耐久", "imageUrl": "images/units/61.jpg", "released": "2026-04-01"},
  {"id": 62, "name": "トールギスⅢ", "limited": false, "type": "支援", "imageUrl": "images/units/62.jpg", "released": "2026-04-01"},
  {"id": 63, "name": "Ex-Sガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/63.jpg", "released": "2026-04-16"},
  {"id": 64, "name": "ガンダム・ファラクト(Season2仕様)", "limited": false, "type": "支援", "imageUrl": "images/units/64.jpg", "released": "2026-04-16"},
  {"id": 65, "name": "ユニコーンガンダム3号機フェネクス", "limited": true, "type": "攻撃", "imageUrl": "images/units/65.jpg", "released": "2026-04-30"},
  {"id": 66, "name": "ハルファスガンダム", "limited": false, "type": "支援", "imageUrl": "images/units/66.jpg", "released": "2026-04-30"},
  {"id": 67, "name": "アトラスガンダム", "limited": false, "type": "攻撃", "imageUrl": "images/units/67.jpg", "released": "2026-05-13"},
  {"id": 68, "name": "グレート・ジオング", "limited": false, "type": "支援", "imageUrl": "images/units/68.jpg", "released": "2026-05-13"},
  {"id": 69, "name": "ナイチンゲール", "limited": true, "type": "支援", "imageUrl": "images/units/69.jpg", "released": "2026-05-31"},
  {"id": 70, "name": "νガンダム(ダブル・フィン・ファンネル装備型)", "limited": false, "type": "耐久", "imageUrl": "images/units/70.jpg", "released": "2026-05-31"},
  {"id": 71, "name": "インフィニットジャスティスガンダム", "limited": false, "type": "攻撃", "imageUrl": "images/units/71.jpg", "released": "2026-06-12", "wrap": "インフィニット|ジャスティスガンダム"},
  {"id": 72, "name": "ストライクノワールガンダム", "limited": false, "type": "支援", "imageUrl": "images/units/72.jpg", "released": "2026-06-12"},
  {"id": 73, "name": "ガンダムF91(ツイン・ヴェスバー装備)", "limited": true, "type": "攻撃", "imageUrl": "images/units/73.jpg", "released": "2026-06-30"},
  {"id": 74, "name": "ガンダムF90(A.D.S.混合装着時)", "limited": false, "type": "支援", "imageUrl": "images/units/74.jpg", "released": "2026-06-30"},
  {"id": 75, "name": "ダリルバルデ(Season2仕様)", "limited": false, "type": "攻撃", "imageUrl": "images/units/75.jpg", "released": "2026-07-16"},
  {"id": 76, "name": "ミカエリス(Season2仕様)", "limited": false, "type": "耐久", "imageUrl": "images/units/76.jpg", "released": "2026-07-16"},
  {"id": 77, "name": "アルトロンガンダム(EW)", "limited": true, "type": "支援", "imageUrl": "images/units/77.jpg", "released": "2026-07-31"},
  {"id": 78, "name": "ガンダムヘビーアームズ改(EW)", "limited": false, "type": "攻撃", "imageUrl": "images/units/78.jpg", "released": "2026-07-31"},
  {"id": 79, "name": "バーサル騎士ガンダム", "limited": true, "type": "攻撃", "imageUrl": "images/units/79.jpg", "released": "2026-08-13"},
  {"id": 80, "name": "三代目頑駄無大将軍", "limited": false, "type": "支援", "imageUrl": "images/units/80.jpg", "released": "2026-08-13", "wrap": "三代目|頑駄無大将軍"},
  {"id": 81, "name": "フルアーマー百式改", "limited": true, "type": "攻撃", "imageUrl": "images/units/81.jpg", "released": "2026-08-31"},
  {"id": 82, "name": "Dガンダム・サード", "limited": false, "type": "支援", "imageUrl": "images/units/82.jpg", "released": "2026-08-31"},
  {"id": 83, "name": "ガンダムアヴァランチアストレア タイプFダッシュ", "limited": false, "type": "耐久", "imageUrl": "images/units/83.jpg", "released": "2026-09-17"},
  {"id": 84, "name": "スサノオ", "limited": false, "type": "攻撃", "imageUrl": "images/units/84.jpg", "released": "2026-09-17"}
];
