-- ④ D1への所持データ保存の前提として、units_master/supporters_masterに実データを投入する。
-- （作成時にスキーマのみ定義され、マスターデータは未投入のままだった。
--   units_ownership/supporters_ownershipのFOREIGN KEYはこのマスターを参照しているため、
--   環境によりFOREIGN KEY制約が有効化されている場合、投入なしでは所持データの保存が失敗する）
-- unit.html/supporter.html の UNITS 配列（id・name・limited・type/healGroup）と完全一致させて生成。
-- 冪等のため、既存データがあれば一旦削除してから投入する

DELETE FROM units_master;
DELETE FROM supporters_master;

INSERT INTO units_master (unit_id, name, limited, type) VALUES (1, 'ガンダム', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (2, 'ガンダムEz8', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (3, 'ストライカーカスタム', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (4, 'ル・シーニュ', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (5, 'νガンダム', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (6, 'サザビー', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (7, 'ユニコーンガンダム（デストロイモード）', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (8, 'ナラティブガンダムA装備', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (9, 'クロスボーンガンダム', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (10, 'フリーダムガンダム', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (11, 'ガンダムエクシア', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (12, 'ガンダム・バルバトス（第6形態）', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (13, 'ガンダム・エアリアル', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (14, 'フェニックスガンダム（能力解放）', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (15, 'ストライクフリーダムガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (16, 'ジャスティスガンダム', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (17, 'Zガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (18, 'ジ・O', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (19, 'ガンダム試作2号機', 1, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (20, 'シャア専用ザク', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (21, 'ガンダムデスサイズヘル(EW)', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (22, 'ビルドストライクガンダム(フルパッケージ)', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (23, 'Hi-νガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (24, 'フォースインパルスガンダム', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (25, 'フルアーマー・ガンダム(サンダーボルト版)', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (26, 'サイコ・ザク', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (27, 'バンシィ・ノルン（デストロイモード）', 1, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (28, 'マスターガンダム', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (29, 'モンスターブラックドラゴン', 1, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (30, '劉備ユニコーンガンダム', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (31, 'フルアーマーΖΖガンダム', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (32, 'キュベレイ(ZZ版)', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (33, 'ジオング', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (34, 'ガンダム・アスタロトリナシメント', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (35, 'ユニコーンガンダム（デストロイモード/覚醒）', 1, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (36, 'ゴッドガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (37, 'ガンダムF91', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (38, 'ガンダム試作3号機', 1, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (39, 'ノイエ・ジール', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (40, 'ガンダム・バルバトスルプスレクス', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (41, 'ガンダム・エアリアル改修型', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (42, 'ブルーディスティニー1号機', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (43, 'シナンジュ', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (44, 'Ξガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (45, 'ペーネロペー', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (46, 'プロヴィデンスガンダム', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (47, 'ケンプファー', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (48, 'ガンダム・キャリバーン', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (49, 'デスティニーガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (50, 'ビグ・ラング', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (51, 'ガンダム・キマリスヴィダール', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (52, 'ガンダムDX', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (53, 'ガンダムヴァサーゴチェストブレイク', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (54, 'ガンダムアストレイ レッドフレーム改', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (55, 'ガンダムアストレイ ゴールドフレーム天ミナ', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (56, 'ガンダムAGE-2 ノーマル', 1, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (57, 'ガンダムAGE-1', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (58, 'グフカスタム', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (59, 'サイコ・ハロ', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (60, 'ウイングガンダムゼロ(EW)', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (61, 'ダブルオーライザー（最終決戦仕様）', 1, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (62, 'トールギスⅢ', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (63, 'Ex-Sガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (64, 'ガンダム・ファラクト(Season2仕様)', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (65, 'ユニコーンガンダム3号機フェネクス', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (66, 'ハルファスガンダム', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (67, 'アトラスガンダム', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (68, 'グレート・ジオング', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (69, 'ナイチンゲール', 1, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (70, 'νガンダム（ダブル・フィン・ファンネル装備型）', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (71, 'インフィニットジャスティスガンダム', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (72, 'ストライクノワールガンダム', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (73, 'ガンダムF91（ツイン・ヴェスバー装備）', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (74, 'ガンダムF90(A.D.S.混合装着時)', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (75, 'ダリルバルデ(Season2仕様)', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (76, 'ミカエリス(Season2仕様)', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (77, 'アルトロンガンダム(EW)', 1, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (78, 'ガンダムヘビーアームズ改(EW)', 0, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (79, 'バーサル騎士ガンダム', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (80, '三代目頑駄無大将軍', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (81, 'フルアーマー百式改', 1, '攻撃');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (82, 'Dガンダム・サード', 0, '支援');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (83, 'ガンダムアヴァランチアストレア タイプFダッシュ(EX)', 0, '耐久');
INSERT INTO units_master (unit_id, name, limited, type) VALUES (84, 'スサノオ(EX)', 0, '攻撃');

INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (1, 'ブライト・ノア&ホワイトベース', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (2, 'フラウ・ボゥ&ホワイトベース', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (3, 'ファ・ユイリィ&アーガマ', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (4, 'ヘンケン・ベッケナー&ラーディッシュ', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (5, 'ビーチャ・オーレグ&ネェル・アーガマ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (6, 'レイン・ミカムラ&ブッド・キャリアー', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (7, 'リリーナ・ドーリアン&ピースミリオン', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (8, 'ティファ・アディール&フリーデン', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (9, 'マリュー・ラミアス&アークエンジェル', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (10, 'アンドリュー・バルトフェルド&エターナル', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (11, 'スメラギ・李・ノリエガ&プトレマイオス', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (12, 'マリナ・イスマイール&プトレマイオス2', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (13, 'オルガ・イツカ&イサリビ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (14, 'クーデリア・藍那・バーンスタイン&イサリビ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (15, 'ミオリネ・レンブラン&学園艦', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (16, 'ラクス・クライン&エターナル', 1, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (17, 'ベルトーチカ・イルマ&アウドムラ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (18, 'エイパー・シナプス&アルビオン', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (19, 'ルクレツィア・ノイン&スーパーソニックトランスポーター', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (20, 'ブライト・ノア&ラー・カイラム(CCA)', 1, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (21, 'クローディア・ペール&ビーハイヴ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (22, 'キョウジ・カッシュ&デビルガンダム第2形態', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (23, '騎士アムロ&天馬ホワイトベース', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (24, 'グレミー・トト&サンドラ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (25, 'ララァ・スン&ザンジバル', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (26, 'オットー・ミタス&ネェル・アーガマ(ロンド・ベル隊仕様)', 1, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (27, 'シーマ・ガラハウ&リリー・マルレーン', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (28, 'アトラ・ミクスタ&ホタルビ', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (29, 'ミネバ・ラオ・ザビ&ガランシェール', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (30, 'ギギ・アンダルシア&ハウンゼン356便', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (31, 'ムルタ・アズラエル&ドミニオン', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (32, 'タリア・グラディス&ミネルバ', 1, '複合');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (33, 'ラスタル・エリオン&スキップジャック級戦艦', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (34, 'ジャミル・ニート&フリーデンⅡ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (35, '風花・アジャー&ローラシア級', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (36, 'グルーデック・エイノア&ディーヴァ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (37, 'エレドア・マシス&ホバートラック', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (38, 'スメラギ・李・ノリエガ&プトレマイオス2', 1, '複合');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (39, 'プロスぺラ&クワイエット・ゼロ', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (40, 'ゾルタン・アッカネン&グルトップ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (41, 'ビンセント・パイク&スパルタン', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (42, 'ナナイ・ミゲル&レウルーラ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (43, 'カガリ・ユラ・アスハ&クサナギ', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (44, 'カロッゾ・ロナ&ザムス・ガル', 1, '複合');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (45, 'ラウダ・ニール&学園艦', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (46, 'ミリアルド・ピースクラフト&リーブラ', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (47, '騎士アムロ(ディジェアーマー)', 0, 'EN回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (48, 'ブライト・ノア&グリプスⅡ', 0, 'HP回復');
INSERT INTO supporters_master (supporter_id, name, limited, skill) VALUES (49, 'シェリリン・ハイド＆エウクレイデス', 0, 'EN回復');
