INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (19, 'UC', '宇宙世紀', 10, '機動戦士ガンダム THE ORIGIN', 'THE ORIGIN', 'U.C.0068-0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (20, 'UC', '宇宙世紀', 20, '機動戦士ガンダム THE ORIGIN MSD', 'ORIGIN MSD', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (1, 'UC', '宇宙世紀', 30, '機動戦士ガンダム', '機動戦士ガンダム', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (21, 'UC', '宇宙世紀', 40, 'MSV', 'MSV', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (22, 'UC', '宇宙世紀', 50, 'MS-X', 'MS-X', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (52, 'UC', '宇宙世紀', 60, 'M-MSV', 'M-MSV', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (47, 'UC', '宇宙世紀', 70, 'MSV-R', 'MSV-R', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (26, 'UC', '宇宙世紀', 80, '機動戦士ガンダム 第08MS小隊', '第08MS小隊', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (28, 'UC', '宇宙世紀', 90, '機動戦士ガンダム外伝 THE BLUE DESTINY', 'THE BLUE DESTINY', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (29, 'UC', '宇宙世紀', 100, '機動戦士ガンダム外伝 ザ・ブルーディスティニー', 'ザ・ブルーディスティニー', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (32, 'UC', '宇宙世紀', 110, '機動戦士ガンダム サンダーボルト', 'サンダーボルト', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (23, 'UC', '宇宙世紀', 120, '機動戦士ガンダム MS IGLOO', 'MS IGLOO', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (24, 'UC', '宇宙世紀', 130, '機動戦士ガンダム MS IGLOO 603', 'MS IGLOO 603', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (25, 'UC', '宇宙世紀', 140, '機動戦士ガンダム MS IGLOO2 重力戦線', 'MS IGLOO2 重力戦線', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (30, 'UC', '宇宙世紀', 150, '機動戦士ガンダム戦記 Lost War Chronicles', 'ガンダム戦記 LWC', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (31, 'UC', '宇宙世紀', 160, '機動戦士ガンダム外伝 ミッシングリンク', 'ミッシングリンク', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (27, 'UC', '宇宙世紀', 170, '機動戦士ガンダム CROSS DIMENSION 0079', 'CROSS DIMENSION 0079', 'U.C.0079');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (33, 'UC', '宇宙世紀', 180, '機動戦士ガンダム0080 ポケットの中の戦争', '0080', 'U.C.0079-0080');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (34, 'UC', '宇宙世紀', 190, '機動戦士ガンダム戦記 BATTLEFIELD RECORD U.C.0081', 'ガンダム戦記 U.C.0081', 'U.C.0081');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (36, 'UC', '宇宙世紀', 200, '機動戦士ガンダム0083 STARDUST MEMORY', '0083', 'U.C.0083');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (37, 'UC', '宇宙世紀', 210, '機動戦士ガンダム0083 REBELLION', '0083 REBELLION', 'U.C.0083');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (38, 'UC', '宇宙世紀', 220, '機動戦士ガンダム ファントム・ブレット', 'ファントム・ブレット', 'U.C.0083');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (48, 'UC', '宇宙世紀', 230, '機動戦士ガンダム MSV-R ジョニー・ライデンの帰還', 'ジョニー・ライデンの帰還', 'U.C.0083');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (39, 'UC', '宇宙世紀', 240, '機動戦士ガンダム カタナ', 'カタナ', 'U.C.0084');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (41, 'UC', '宇宙世紀', 250, 'ADVANCE OF Ζ ティターンズの旗のもとに', 'ADVANCE OF Ζ', 'U.C.0084-0087');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (35, 'UC', '宇宙世紀', 260, '機動戦士Gundam GQuuuuuuX', 'ジークアクス', 'U.C.0085');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (40, 'UC', '宇宙世紀', 270, '機動戦士ガンダム エコール・デュ・シエル 天空の学校', 'エコール・デュ・シエル', 'U.C.0085-0088');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (42, 'UC', '宇宙世紀', 280, '機動戦士Ζガンダム', '機動戦士Ζガンダム', 'U.C.0087');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (2, 'UC', '宇宙世紀', 290, '機動戦士Ζガンダム A New Translation', 'Ζ A New Translation', 'U.C.0087');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (43, 'UC', '宇宙世紀', 300, '機動戦士Ζガンダム Define', 'Ζガンダム Define', 'U.C.0087');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (44, 'UC', '宇宙世紀', 310, 'Z-MSV', 'Z-MSV', 'U.C.0087');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (45, 'UC', '宇宙世紀', 320, 'ガンダム新体験0087 グリーンダイバーズ', 'グリーンダイバーズ', 'U.C.0087');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (46, 'UC', '宇宙世紀', 330, 'GUNDAM SENTINEL', 'ガンダム・センチネル', 'U.C.0088');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (3, 'UC', '宇宙世紀', 340, '機動戦士ガンダムΖΖ', '機動戦士ガンダムΖΖ', 'U.C.0088-0089');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (50, 'UC', '宇宙世紀', 350, 'ダブルフェイク アンダー・ザ・ガンダム', 'ダブルフェイク', 'U.C.0090');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (49, 'UC', '宇宙世紀', 360, '機動戦士ガンダム ヴァルプルギス', 'ヴァルプルギス', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (4, 'UC', '宇宙世紀', 370, '機動戦士ガンダム 逆襲のシャア', '逆襲のシャア', 'U.C.0093');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (51, 'UC', '宇宙世紀', 380, 'CCA-MSV', 'CCA-MSV', 'U.C.0093');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (5, 'UC', '宇宙世紀', 390, '機動戦士ガンダムUC', '機動戦士ガンダムUC', 'U.C.0096');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (53, 'UC', '宇宙世紀', 400, 'UC-MSV', 'UC-MSV', 'U.C.0096');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (6, 'UC', '宇宙世紀', 410, '機動戦士ガンダムNT', '機動戦士ガンダムNT', 'U.C.0097');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (7, 'UC', '宇宙世紀', 420, '機動戦士ガンダム 閃光のハサウェイ', '閃光のハサウェイ', 'U.C.0105');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (55, 'UC', '宇宙世紀', 430, '機動戦士ガンダムF90', 'ガンダムF90', 'U.C.0120');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (56, 'UC', '宇宙世紀', 440, '機動戦士ガンダムF90クラスター', 'F90クラスター', 'U.C.0120');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (58, 'UC', '宇宙世紀', 450, '機動戦士ガンダムF91 フォーミュラー戦記0122', 'フォーミュラー戦記0122', 'U.C.0122');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (8, 'UC', '宇宙世紀', 460, '機動戦士ガンダムF91', 'ガンダムF91', 'U.C.0123');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (57, 'UC', '宇宙世紀', 470, 'F91-MSV', 'F91-MSV', 'U.C.0123');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (59, 'UC', '宇宙世紀', 480, '機動戦士ガンダム シルエットフォーミュラ91', 'シルエットフォーミュラ91', 'U.C.0123');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (60, 'UC', '宇宙世紀', 490, '機動戦士クロスボーン・ガンダム', 'クロスボーン・ガンダム', 'U.C.0133');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (61, 'UC', '宇宙世紀', 500, '機動戦士Vガンダム', '機動戦士Vガンダム', 'U.C.0153');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (85, 'UC', 'リギルド・センチュリー', 510, 'ガンダム Gのレコンギスタ', 'Gのレコンギスタ', 'R.G.1014');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (9, 'ALT', '未来世紀', 1010, '機動武闘伝Gガンダム', '機動武闘伝Gガンダム', 'F.C.60');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (10, 'ALT', 'アフターコロニー', 1020, '新機動戦記ガンダムW', '新機動戦記ガンダムW', 'A.C.195');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (62, 'ALT', 'アフターコロニー', 1030, '新機動戦記ガンダムW Endless Waltz 敗者たちの栄光', 'EW 敗者たちの栄光', 'A.C.195');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (64, 'ALT', 'アフターコロニー', 1040, '新機動戦記ガンダムW デュアルストーリー G-UNIT', 'ガンダムW G-UNIT', 'A.C.195');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (11, 'ALT', 'アフターコロニー', 1050, '新機動戦記ガンダムW Endless Waltz', 'ガンダムW EW', 'A.C.196');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (63, 'ALT', 'アフターコロニー', 1060, '新機動戦記ガンダムW BATTLEFIELD OF PACIFIST', 'BATTLEFIELD OF PACIFIST', 'A.C.197');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (12, 'ALT', 'アフターウォー', 1070, '機動新世紀ガンダムX', '機動新世紀ガンダムX', 'A.W.0015');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (65, 'ALT', '正暦', 1080, '∀ガンダム', '∀ガンダム', '正暦2343');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (13, 'ALT', 'コズミック・イラ', 1090, '機動戦士ガンダムSEED', 'ガンダムSEED', 'C.E.71');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (71, 'ALT', 'コズミック・イラ', 1100, '機動戦士ガンダムSEED Recollection', 'SEED Recollection', 'C.E.71');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (66, 'ALT', 'コズミック・イラ', 1110, '機動戦士ガンダムSEED MSV', 'SEED MSV', 'C.E.71');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (67, 'ALT', 'コズミック・イラ', 1120, '機動戦士ガンダムSEED ASTRAY', 'SEED ASTRAY', 'C.E.71');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (68, 'ALT', 'コズミック・イラ', 1130, '機動戦士ガンダムSEED ASTRAY R', 'SEED ASTRAY R', 'C.E.71');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (69, 'ALT', 'コズミック・イラ', 1140, '機動戦士ガンダムSEED ASTRAY B', 'SEED ASTRAY B', 'C.E.71');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (75, 'ALT', 'コズミック・イラ', 1150, '機動戦士ガンダムSEED ASTRAY 天空の皇女', 'ASTRAY 天空の皇女', 'C.E.72');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (70, 'ALT', 'コズミック・イラ', 1160, '機動戦士ガンダムSEED X ASTRAY', 'SEED X ASTRAY', 'C.E.72-73');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (14, 'ALT', 'コズミック・イラ', 1170, '機動戦士ガンダムSEED DESTINY', 'SEED DESTINY', 'C.E.73');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (72, 'ALT', 'コズミック・イラ', 1180, '機動戦士ガンダムSEED DESTINY MSV', 'DESTINY MSV', 'C.E.73');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (73, 'ALT', 'コズミック・イラ', 1190, '機動戦士ガンダムSEED C.E.73 STARGAZER', 'STARGAZER', 'C.E.73');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (74, 'ALT', 'コズミック・イラ', 1200, '機動戦士ガンダムSEED VS ASTRAY', 'SEED VS ASTRAY', 'C.E.73-74');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (76, 'ALT', 'コズミック・イラ', 1210, '機動戦士ガンダムSEED FREEDOM', 'SEED FREEDOM', 'C.E.75');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (77, 'ALT', '西暦', 1220, '機動戦士ガンダム00P', 'ガンダム00P', 'A.D.2301-2307');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (15, 'ALT', '西暦', 1230, '機動戦士ガンダム00', 'ガンダム00', 'A.D.2307-2314');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (81, 'ALT', '西暦', 1240, 'ソレスタルビーイング', 'ソレスタルビーイング', 'A.D.2307');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (78, 'ALT', '西暦', 1250, '機動戦士ガンダム00F', 'ガンダム00F', 'A.D.2308-2312');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (80, 'ALT', '西暦', 1260, '機動戦士ガンダム00V', 'ガンダム00V', 'A.D.2307-2312');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (79, 'ALT', '西暦', 1270, '機動戦士ガンダム00I', 'ガンダム00I', 'A.D.2312-2314');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (16, 'ALT', 'アドバンスド・ジェネレーション', 1280, '機動戦士ガンダムAGE', 'ガンダムAGE', 'A.G.115-164');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (83, 'ALT', 'アドバンスド・ジェネレーション', 1290, '機動戦士ガンダムAGE UNKNOWN SOLDIERS', 'AGE UNKNOWN SOLDIERS', 'A.G.');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (82, 'ALT', 'アドバンスド・ジェネレーション', 1300, '機動戦士ガンダムAGE 〜MEMORY OF EDEN〜', 'AGE MEMORY OF EDEN', 'A.G.');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (84, 'ALT', 'アドバンスド・ジェネレーション', 1310, '機動戦士ガンダムAGE EXA-LOG', 'AGE EXA-LOG', 'A.G.');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (17, 'ALT', 'ポスト・ディザスター', 1320, '機動戦士ガンダム 鉄血のオルフェンズ', '鉄血のオルフェンズ', 'P.D.323');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (88, 'ALT', 'ポスト・ディザスター', 1330, '機動戦士ガンダム 鉄血のオルフェンズ MSV', '鉄血のオルフェンズ MSV', 'P.D.323');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (86, 'ALT', 'ポスト・ディザスター', 1340, '機動戦士ガンダム 鉄血のオルフェンズ 月鋼', '鉄血 月鋼', 'P.D.325');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (87, 'ALT', 'ポスト・ディザスター', 1350, '機動戦士ガンダム 鉄血のオルフェンズ ウルズハント', '鉄血 ウルズハント', 'P.D.325');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (89, 'ALT', 'アド・ステラ', 1360, '機動戦士ガンダム 水星の魔女 PROLOGUE', '水星の魔女 PROLOGUE', 'A.S.107');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (18, 'ALT', 'アド・ステラ', 1370, '機動戦士ガンダム 水星の魔女', '水星の魔女', 'A.S.122');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (92, 'ETC', 'ビルドシリーズ', 2010, 'プラモ狂四郎', 'プラモ狂四郎', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (90, 'ETC', 'ビルドシリーズ', 2020, '模型戦士ガンプラビルダーズ ビギニングG', 'ガンプラビルダーズ', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (91, 'ETC', 'ビルドシリーズ', 2030, 'ガンダムビルドファイターズ', 'ビルドファイターズ', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (94, 'ETC', 'SDガンダム', 2040, 'SDガンダム外伝 ジークジオン編', 'SDガンダム外伝', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (98, 'ETC', 'SDガンダム', 2050, 'SDガンダム外伝 ラクロアンヒーローズ', 'ラクロアンヒーローズ', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (93, 'ETC', 'SDガンダム', 2060, 'SD戦国伝', 'SD戦国伝', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (95, 'ETC', 'SDガンダム', 2070, 'SDコマンド戦記 G-ARMS', 'SDコマンド戦記', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (96, 'ETC', 'SDガンダム', 2080, 'SDガンダムワールド 三国創傑伝', '三国創傑伝', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (97, 'ETC', 'SDガンダム', 2090, 'SDガンダムワールド ガチャポン戦士 スクランブルウォーズ', 'ガチャポン戦士', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (100, 'ETC', 'SDガンダム', 2100, 'SDガンダムGX', 'SDガンダムGX', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (106, 'ETC', 'ゲーム・その他', 2110, 'G GENERATIONシリーズ', 'G GENERATION', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (103, 'ETC', 'ゲーム・その他', 2120, '機動戦士ガンダム ギレンの野望', 'ギレンの野望', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (104, 'ETC', 'ゲーム・その他', 2130, '機動戦士ガンダム 戦場の絆', '戦場の絆', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (105, 'ETC', 'ゲーム・その他', 2140, '機動戦士ガンダム エクストリームバーサス', 'エクストリームバーサス', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (101, 'ETC', 'ゲーム・その他', 2150, 'GUNDAM THE BATTLE MASTER', 'BATTLE MASTER', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (102, 'ETC', 'ゲーム・その他', 2160, 'GUNDAM TACTICS MOBILITY FLEET0079', 'GUNDAM TACTICS', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (99, 'ETC', 'ゲーム・その他', 2170, 'GUNDAM EVOLVE', 'GUNDAM EVOLVE', '');
INSERT OR REPLACE INTO works_master (work_id, era, universe, sort_order, name, short_name, timeline_label) VALUES (54, 'ETC', 'ゲーム・その他', 2180, 'お台場ユニコーンガンダム立像', 'お台場ユニコーン立像', '');
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (1, 1);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (2, 26);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (3, 39);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (4, 2);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (5, 4);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (6, 4);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (7, 5);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (8, 6);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (9, 60);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (10, 13);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (11, 15);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (12, 17);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (13, 18);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (14, 106);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (15, 14);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (16, 13);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (17, 2);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (18, 2);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (19, 36);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (20, 1);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (21, 11);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (22, 91);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (23, 4);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (24, 14);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (25, 32);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (26, 32);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (27, 5);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (28, 9);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (29, 94);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (30, 96);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (31, 3);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (32, 3);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (33, 1);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (34, 86);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (35, 5);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (36, 9);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (37, 8);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (38, 36);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (39, 36);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (40, 17);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (41, 18);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (42, 28);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (43, 5);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (44, 7);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (45, 7);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (46, 13);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (47, 33);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (48, 18);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (49, 14);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (50, 36);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (51, 17);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (52, 12);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (53, 12);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (54, 67);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (55, 75);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (56, 16);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (57, 16);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (58, 26);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (59, 106);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (60, 11);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (61, 15);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (62, 11);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (63, 46);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (64, 18);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (65, 6);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (66, 106);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (67, 32);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (68, 1);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (69, 4);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (70, 51);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (71, 14);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (72, 73);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (73, 57);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (74, 55);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (75, 18);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (76, 18);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (77, 11);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (78, 11);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (79, 94);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (80, 93);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (81, 3);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (82, 50);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (83, 78);
INSERT OR REPLACE INTO unit_work_map (unit_id, work_id) VALUES (84, 15);
