DELETE FROM supporters_leader_targets;
DELETE FROM supporters_leader_rules;
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (1, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (2, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (3, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (4, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (5, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (6, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (7, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (8, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (9, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (10, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (11, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (12, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (13, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (14, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (15, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (16, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (17, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (18, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (19, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (20, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (21, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (22, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (23, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (24, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (25, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (26, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (27, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (28, 1, 20, NULL, NULL, 28);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (28, 2, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (29, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (30, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (31, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (32, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (33, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (34, 1, 20, NULL, NULL, 28);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (34, 2, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (35, 1, 20, NULL, NULL, 28);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (35, 2, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (36, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (37, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (38, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (39, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (40, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (41, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (42, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (43, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (44, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (45, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (46, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (47, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (48, 1, 25, 30, 33, 36);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (49, 1, 20, NULL, NULL, 28);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (49, 2, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (50, 1, 30, 36, 40, 44);
INSERT INTO supporters_leader_rules (supporter_id, rule_no, rate_lv0, rate_lv1, rate_lv2, rate_lv3) VALUES (50, 2, 25, 30, 33, 36);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (1, 1, 1, 'work', 1);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (2, 1, 1, 'tag', 49);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (3, 1, 1, 'tag', 46);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (4, 1, 1, 'work', 42);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (4, 1, 1, 'work', 2);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (5, 1, 1, 'tag', 49);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (6, 1, 1, 'tag', 47);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (7, 1, 1, 'work', 10);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (8, 1, 1, 'tag', 48);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (9, 1, 1, 'work', 13);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (10, 1, 1, 'tag', 9);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (11, 1, 1, 'work', 15);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (12, 1, 1, 'tag', 47);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (13, 1, 1, 'work', 17);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (14, 1, 1, 'tag', 46);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (15, 1, 1, 'work', 18);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (16, 1, 1, 'tag', 48);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (17, 1, 1, 'tag', 32);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (18, 1, 1, 'tag', 6);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (19, 1, 1, 'tag', 11);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (20, 1, 1, 'tag', 18);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (21, 1, 1, 'work', 1);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (22, 1, 1, 'tag', 27);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (23, 1, 1, 'tag', 11);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (23, 1, 1, 'tag', 72);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (24, 1, 1, 'work', 3);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (25, 1, 1, 'tag', 115);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (26, 1, 1, 'tag', 134);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (27, 1, 1, 'work', 36);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (27, 1, 1, 'tag', 6);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (28, 1, 1, 'work', 17);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (28, 2, 1, 'work', 17);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (28, 2, 2, 'tag', 37);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (29, 1, 1, 'tag', 80);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (29, 1, 1, 'work', 5);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (30, 1, 1, 'work', 4);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (30, 1, 1, 'work', 7);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (31, 1, 1, 'tag', 27);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (32, 1, 1, 'tag', 49);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (33, 1, 1, 'tag', 134);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (34, 1, 1, 'work', 12);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (34, 2, 1, 'work', 12);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (34, 2, 2, 'tag', 127);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 1, 1, 'tag', 59);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 1, 'tag', 59);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 2, 'work', 67);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 2, 'work', 68);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 2, 'work', 69);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 2, 'work', 70);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 2, 'work', 74);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (35, 2, 2, 'work', 75);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (36, 1, 1, 'work', 16);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (36, 1, 1, 'tag', 42);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (37, 1, 1, 'work', 26);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (37, 1, 1, 'tag', 2);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (38, 1, 1, 'tag', 45);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (39, 1, 1, 'tag', 50);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (40, 1, 1, 'tag', 8);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (40, 1, 1, 'work', 6);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (41, 1, 1, 'tag', 3);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (41, 1, 1, 'tag', 1);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (42, 1, 1, 'tag', 18);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (43, 1, 1, 'work', 14);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (44, 1, 1, 'tag', 6);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (45, 1, 1, 'tag', 45);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (46, 1, 1, 'tag', 137);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (46, 1, 1, 'work', 11);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (47, 1, 1, 'tag', 135);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (47, 1, 1, 'tag', 72);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (48, 1, 1, 'tag', 50);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (49, 1, 1, 'work', 15);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (49, 2, 1, 'work', 15);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (49, 2, 2, 'tag', 98);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (50, 1, 1, 'tag', 136);
INSERT INTO supporters_leader_targets (supporter_id, rule_no, cond_no, target_kind, target_id) VALUES (50, 2, 1, 'work', 61);
